### ISSUE TITLE
migrate compileSdkVersion 31 to 30

### ISSUE THREAD

**Issue by saurabh88888888** [braver-tool/Android11FilePicker#1]
for compileSdkVersion 30 this library not sync and after migrating compileSdkVersion 30 to 31 it occurs error

Compilation failed; see the compiler error output for details.

build.gradle file:-
 compileSdkVersion 31
    //buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.ultimate.ultimatesmartsystem"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode 37
        versionName "2.3.5"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        useLibrary 'org.apache.http.legacy'

    }

any solution for that its very argent for me.
thank you
